version: '3'

services:
  app:
    build:
      context: app
    networks:
      - my-network

  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/default.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:
